/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface _Master_ {
  IndexerPayload: IndexerPayload;
  IndexerOutput: IndexerOutput;
}
export interface IndexerPayload {
  tags?: string[] | null;
  tags_or?: boolean | null;
  type?: string | null;
  msg_sender?: string | null;
  block_timestamp_gte?: number | null;
  block_timestamp_lte?: number | null;
  value_gte?: number | null;
  value_lte?: number | null;
  eth_value_gte?: string | null;
  eth_value_lte?: string | null;
  module?: string | null;
  input_index?: number | null;
  app_contract?: string | null;
  order_by?: string | null;
  order_dir?: string | null;
  page?: number | null;
  page_size?: number | null;
}
export interface IndexerOutput {
  data: OutputIndex[];
  total: number;
  page: number;
}
export interface OutputIndex {
  type: string;
  module: string;
  class_name: string;
  input_index: number;
  output_index?: number;
  app_contract?: string;
}
