/* eslint-disable */
/**
 * This file was automatically generated by cartesapp.template_generator.
 * DO NOT MODIFY IT BY HAND. Instead, run the generator,
 */

import { hexToBigInt, isHex, toHex } from "viem";
import {
  type InputAdded,
  type Input as CartesiInput,
  type Report as CartesiReport,
  type Output as CartesiOutput,
} from "@cartesi/viem";
import Ajv from "ajv";
import addFormats from "ajv-formats";

import {
  genericAdvanceInput,
  genericInspect,
  type IOType,
  type Models,
  IOData,
  Input,
  Output,
  type MutationOptions,
  type QueryOptions,
  CONVENTIONAL_TYPES,
  decodeToConventionalTypes,
  type AdvanceResult,
  listAdvanceResults,
  OutputWithProof,
} from "../cartesapp/utils";
import { type InspectOptions, type InspectReport } from "../cartesapp/inspect";

import * as ifaces from "./ifaces.d";


/**
 * Configs
 */

const ajv = new Ajv();
addFormats(ajv);
ajv.addFormat("biginteger", (data) => {
  if (!isHex(data)) return false;
  const dataTovalidate = hexToBigInt(data);
  return typeof dataTovalidate == "bigint";
});
const MAX_SPLITTABLE_OUTPUT_SIZE = 4194247;

/*
 * Mutations/Advances
 */


/*
 * Queries/Inspects
 */

export async function indexerQuery(
    inputData: ifaces.IndexerPayload,
    options?:QueryOptions
):Promise<InspectReport|any> {
  const selectorInfo = 'indexer_indexerQuery';
  const data: IndexerPayload = new IndexerPayload(inputData);
  const output: InspectReport =
    await genericInspect<ifaces.IndexerPayload>(
      data,
      selectorInfo,
      options
    );
  if (options?.decode) {
    return decodeToModel(output,options.decodeModel || "json");
  }
  return output;
}




/**
 * Models Decoders/Exporters
 */

export function decodeToModel(
  data: CartesiInput | CartesiOutput | CartesiReport | InspectReport,
  modelName: string
): any {
  if (modelName == undefined) throw new Error("undefined model");
  if (CONVENTIONAL_TYPES.includes(modelName)) {
    if ((data as CartesiOutput).decodedData)
      return decodeToConventionalTypes((data as CartesiOutput).decodedData.payload, modelName);
    return decodeToConventionalTypes(data.rawData, modelName);
  }
  const decoder = models[modelName].decoder;
  if (decoder == undefined) throw new Error("undefined decoder");
  return decoder(data);
}

export function exportToModel(data: any, modelName: string): string {
  const exporter = models[modelName].exporter;
  if (exporter == undefined) throw new Error("undefined exporter");
  return exporter(data);
}

// Query IndexerPayload

// export class IndexerPayloadInput extends Input<ifaces.IndexerPayload> {
//   constructor(data: CartesiInput) {
//     super(models['IndexerPayload'],data);
//   }
// }
// export function decodeToIndexerPayloadInput(
//   data: CartesiInput | CartesiOutput | CartesiReport | InspectReport
// ): IndexerPayloadInput {
//   return new IndexerPayloadInput(data as CartesiInput);
// }

export class IndexerPayload extends IOData<ifaces.IndexerPayload> {
  constructor(data: ifaces.IndexerPayload, validate: boolean = true) {
    super(models['IndexerPayload'],data,validate);
  }
}
export function exportToIndexerPayload(
  data: ifaces.IndexerPayload
): string {
  const dataToExport: IndexerPayload = new IndexerPayload(data);
  return dataToExport.export();
}
// Report IndexerOutput

export class IndexerOutput extends Output<ifaces.IndexerOutput> {
  constructor(output: CartesiReport | InspectReport) {
    super(models['IndexerOutput'],output);
  }
}
export function decodeToIndexerOutput(
  output: CartesiInput | CartesiOutput | CartesiReport | InspectReport
): IndexerOutput {
  return new IndexerOutput(output as CartesiReport);
}


/**
 * Model
 */

export const models: Models = {
  'IndexerPayload': {
    ioType:"queryJsonPayload",
    abiTypes:[],
    params:['tags', 'tags_or', 'type', 'msg_sender', 'block_timestamp_gte', 'block_timestamp_lte', 'value_gte', 'value_lte', 'eth_value_gte', 'eth_value_lte', 'module', 'input_index', 'app_contract', 'order_by', 'order_dir', 'page', 'page_size'],
    // decoder: decodeToIndexerPayloadInput,
    exporter: exportToIndexerPayload,
    validator: ajv.compile<ifaces.IndexerPayload>(
      JSON.parse(
        '{"title": "IndexerPayload", "type": "object", "properties": {"tags": {"title": "Tags", "type": "array", "items": {"type": "string"}}, "tags_or": {"title": "Tags Or", "type": "boolean"}, "type": {"title": "Type", "type": "string"}, "msg_sender": {"title": "Msg Sender", "type": "string"}, "block_timestamp_gte": {"title": "Block Timestamp Gte", "type": "integer"}, "block_timestamp_lte": {"title": "Block Timestamp Lte", "type": "integer"}, "value_gte": {"title": "Value Gte", "type": "integer"}, "value_lte": {"title": "Value Lte", "type": "integer"}, "eth_value_gte": {"title": "Eth Value Gte", "type": "string"}, "eth_value_lte": {"title": "Eth Value Lte", "type": "string"}, "module": {"title": "Module", "type": "string"}, "input_index": {"title": "Input Index", "type": "integer"}, "app_contract": {"title": "App Contract", "type": "string"}, "order_by": {"title": "Order By", "type": "string"}, "order_dir": {"title": "Order Dir", "type": "string"}, "page": {"title": "Page", "type": "integer"}, "page_size": {"title": "Page Size", "type": "integer"}}}'
      )
    )
  },
  'IndexerOutput': {
    ioType:"report",
    abiTypes:[],
    params:['data', 'total', 'page'],
    decoder: decodeToIndexerOutput,
    validator: ajv.compile<ifaces.IndexerOutput>(
      JSON.parse(
        '{"title": "IndexerOutput", "type": "object", "properties": {"data": {"title": "Data", "type": "array", "items": {"$ref": "#/definitions/OutputIndex"}}, "total": {"title": "Total", "type": "integer"}, "page": {"title": "Page", "type": "integer"}}, "required": ["data", "total", "page"], "definitions": {"OutputIndex": {"title": "OutputIndex", "type": "object", "properties": {"type": {"title": "Type", "type": "string"}, "module": {"title": "Module", "type": "string"}, "class_name": {"title": "Class Name", "type": "string"}, "input_index": {"title": "Input Index", "type": "integer"}, "output_index": {"title": "Output Index", "type": "integer"}, "app_contract": {"title": "App Contract", "type": "string"}}, "required": ["type", "module", "class_name", "input_index"]}}}'
      )
    )
  },
  };